### ISSUE TITLE
Stemming Issues

### ISSUE THREAD

**Issue by greenonion** [skroutz/elasticsearch-analysis-turkishstemmer#4]
- [ ] `Çini` (ceramics) stems to `Çin` (China)
- [ ] `Salı` (Tuesday) stems to `sal`
- [ ] `kuma` (second wife!) stems to `kum` (sand)
- [ ] `vibe` stems to `vip`

**Comment by ahurriyetoglu** [comment]
Salı means Tuesday, NOT Şalı.

**Comment by greenonion** [comment]
@ahurriyetoglu ah, yes, you're right, thanks! However, `salı`stems to `sal` which is still wrong, so I guess we should fix both of these. 

I think stemming `Şalı` to `Şal` doesn't make any sense though, so we should probably add an exception there nevertheless.

**Comment by ahurriyetoglu** [comment]
"Sal" is a proper Turkish word, "Salı" as well. This is ambiguity. I think stemming "Şalı" to "Şal" is correct.

**Comment by greenonion** [comment]
Alright, let's only fix `Salı` then :) Thanks a lot!
